### ISSUE TITLE
Road to 11ty site update

### ISSUE THREAD

**Issue by ninjamuffin99** [HaxeFlixel/haxeflixel.com#223]
In December I started work on a site overhaul using 11ty (#219 ), and I got a decent little handle on things. However instead of working complete top down in that way, I think we can slowly work and make things easier to "port" along the way, so I will use this as a bit of a task tracker for that work!

## Add 11ty as a site build step

- [x] Github actions #230 
- [x] package.json script #230 
- [x] update readme.md with instructions for building
- [x] document the folder layout for the site

## Convert site pages into liquid
    
- [x] /blog and blog-posts #230 
    - [x] Port the fundraiser blog post, it has extra rendering needed
- [x] Add the site search partial back
- [x] /showcase
- [x] /documentation (main page with all the documentation links) - might require figuring out cloning for flixel-docs
- [x] /documentation/docs (page for documentation)
    - [x] convert the docs files from .html.md to just .md
    - [x] general porting of docpad -> 11ty
- [x] /demos
~~- [ ] /snippets + move that into flixel-docs?~~ Will do in another phase!
- [x] /home
~~- [ ] /api - this is served via api.haxeflixel.com, but maybe can setup a redirect from there to haxeflixel.com/api ?~~ Will do in another phase!

## Misc Tasks
- [x] Fix the platforms SVG colors when in darkmode
- [x] Fix github buttons colors when in darkmode
- [x] Fix white appearing behind X/Twitter buttons in darkmode
- [x] #245 (note: only doing step 1 of this gh issue for mvp)
- [x] Fully remove all old Docker stuff
- [x] Add title to metadata
- [x] Move all images to new base level folder (keep internal structure?)
- [x] Documentation pages that need to be fixed
    - [x] Troubleshooting
    - [x] Introduction To Haxe
    - [x] Edit Button properly links to github
    - [x] Community Tutorials

There are likely more on the todo for this, but this is a start I believe

**Comment by ninjamuffin99** [comment]
I believe I've found a good path forward to begin 11ty porting. With 11ty, you can selectively add files to render, so I think I will slowly "port" some pages to 11ty, and then essentially add it as a build step
